### ISSUE TITLE
React Audit

### ISSUE THREAD

**Issue by macfeosfiamy** [stake-house/wagyu#34]
General React audit by someone who is a more experienced React developer, including usage of child_process, error handling, etc

**Comment by peebeejay** [comment]
first pass notes:

1. could use react hooks for react router instead
2. translations
3. shared typography components for commonly used text / header
4. nit: would add a few new prettier rules for spacing & max line length
5. more use of hooks overall
6. nit: would rename a bunch of the colors, styled components, reorder imports, remove unused imports, + more housekeeping
7. nit: would use explicit exports instead of default (more explicit)
8. nit: would change the font to use rem, so text adjusts nicely w font size
9. would extract a number of functions from Status.tsx into a utils file, and generally spit it up
10. would modify Status.tsx to use enum items to represent status
11. could change styling to remove need for <br /> - should use padding, margin and flex
12. could introduce error boundaries, suspense, a context higher up in the tree to store app state

**Comment by colfax23** [comment]
Per our chat, @peebeejay can you please create Issues for each of these?
Storybook
Typography components
README for guidelines for contributions
Reconfigure directory structure
Use react hooks for react router instead
Infrastructure for translations
Housekeeping:
- would rename a bunch of the colors, styled components, reorder imports, remove unused imports, + more housekeeping
- would use explicit exports instead of default (more explicit)
- would change the font to use rem, so text adjusts nicely w font size
Refactor Status page
App wide context
Introduce top level error boundary, investigate how works with electron
Refactor System Check

**Comment by colfax23** [comment]
Done.  Thanks @peebeejay great work.
